-- PostgreSQL foreign keys and secondary indexes for TDA Pekanbaru.
-- Apply only after all D1 rows have been imported successfully.

ALTER TABLE "activities" ADD CONSTRAINT "fk_activities_task_id" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id");
ALTER TABLE "activity_logs" ADD CONSTRAINT "fk_activity_logs_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "attendance_events" ADD CONSTRAINT "fk_attendance_events_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id");
ALTER TABLE "attendance_events" ADD CONSTRAINT "fk_attendance_events_treasury_account_id" FOREIGN KEY ("treasury_account_id") REFERENCES "treasury_accounts" ("id");
ALTER TABLE "attendance_events" ADD CONSTRAINT "fk_attendance_events_income_task_id" FOREIGN KEY ("income_task_id") REFERENCES "program_tasks" ("id");
ALTER TABLE "attendance_events" ADD CONSTRAINT "fk_attendance_events_created_by_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "attendance_participants" ADD CONSTRAINT "fk_attendance_participants_payment_verified_by_user_id" FOREIGN KEY ("payment_verified_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "attendance_participants" ADD CONSTRAINT "fk_attendance_participants_payment_treasury_account_id" FOREIGN KEY ("payment_treasury_account_id") REFERENCES "treasury_accounts" ("id");
ALTER TABLE "attendance_participants" ADD CONSTRAINT "fk_attendance_participants_payment_received_by_user_id" FOREIGN KEY ("payment_received_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "attendance_participants" ADD CONSTRAINT "fk_attendance_participants_event_id" FOREIGN KEY ("event_id") REFERENCES "attendance_events" ("id");
ALTER TABLE "attendance_participants" ADD CONSTRAINT "fk_attendance_participants_checked_in_by_user_id" FOREIGN KEY ("checked_in_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "membership_registrations" ADD CONSTRAINT "fk_membership_registrations_treasury_account_id" FOREIGN KEY ("treasury_account_id") REFERENCES "treasury_accounts" ("id");
ALTER TABLE "membership_registrations" ADD CONSTRAINT "fk_membership_registrations_payment_verified_by_user_id" FOREIGN KEY ("payment_verified_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "membership_settings" ADD CONSTRAINT "fk_membership_settings_treasury_account_id" FOREIGN KEY ("treasury_account_id") REFERENCES "treasury_accounts" ("id");
ALTER TABLE "notification_runs" ADD CONSTRAINT "fk_notification_runs_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id");
ALTER TABLE "program_approvals" ADD CONSTRAINT "fk_program_approvals_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id");
ALTER TABLE "program_approvals" ADD CONSTRAINT "fk_program_approvals_approver_user_id" FOREIGN KEY ("approver_user_id") REFERENCES "users" ("id");
ALTER TABLE "program_evaluations" ADD CONSTRAINT "fk_program_evaluations_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id");
ALTER TABLE "program_evaluations" ADD CONSTRAINT "fk_program_evaluations_created_by_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "program_expenses" ADD CONSTRAINT "fk_program_expenses_treasury_account_id" FOREIGN KEY ("treasury_account_id") REFERENCES "treasury_accounts" ("id");
ALTER TABLE "program_expenses" ADD CONSTRAINT "fk_program_expenses_task_id" FOREIGN KEY ("task_id") REFERENCES "program_tasks" ("id");
ALTER TABLE "program_expenses" ADD CONSTRAINT "fk_program_expenses_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id");
ALTER TABLE "program_expenses" ADD CONSTRAINT "fk_program_expenses_created_by_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "program_feedback_answers" ADD CONSTRAINT "fk_program_feedback_answers_submission_id" FOREIGN KEY ("submission_id") REFERENCES "program_feedback_submissions" ("id");
ALTER TABLE "program_feedback_answers" ADD CONSTRAINT "fk_program_feedback_answers_question_id" FOREIGN KEY ("question_id") REFERENCES "program_feedback_questions" ("id");
ALTER TABLE "program_feedback_questions" ADD CONSTRAINT "fk_program_feedback_questions_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id");
ALTER TABLE "program_feedback_submissions" ADD CONSTRAINT "fk_program_feedback_submissions_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id");
ALTER TABLE "program_feedback_submissions" ADD CONSTRAINT "fk_program_feedback_submissions_event_id" FOREIGN KEY ("event_id") REFERENCES "attendance_events" ("id");
ALTER TABLE "program_feedback_submissions" ADD CONSTRAINT "fk_program_feedback_submissions_participant_id" FOREIGN KEY ("participant_id") REFERENCES "attendance_participants" ("id");
ALTER TABLE "program_incomes" ADD CONSTRAINT "fk_program_incomes_treasury_account_id" FOREIGN KEY ("treasury_account_id") REFERENCES "treasury_accounts" ("id");
ALTER TABLE "program_incomes" ADD CONSTRAINT "fk_program_incomes_task_id" FOREIGN KEY ("task_id") REFERENCES "program_tasks" ("id");
ALTER TABLE "program_incomes" ADD CONSTRAINT "fk_program_incomes_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id");
ALTER TABLE "program_incomes" ADD CONSTRAINT "fk_program_incomes_created_by_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "program_lpj" ADD CONSTRAINT "fk_program_lpj_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id");
ALTER TABLE "program_lpj" ADD CONSTRAINT "fk_program_lpj_updated_by_user_id" FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "program_publications" ADD CONSTRAINT "fk_program_publications_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id") ON DELETE CASCADE;
ALTER TABLE "program_publications" ADD CONSTRAINT "fk_program_publications_updated_by_user_id" FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "program_task_divisions" ADD CONSTRAINT "fk_program_task_divisions_task_id" FOREIGN KEY ("task_id") REFERENCES "program_tasks" ("id");
ALTER TABLE "program_task_divisions" ADD CONSTRAINT "fk_program_task_divisions_division_id" FOREIGN KEY ("division_id") REFERENCES "divisions" ("id");
ALTER TABLE "program_tasks" ADD CONSTRAINT "fk_program_tasks_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id");
ALTER TABLE "programs" ADD CONSTRAINT "fk_programs_period_id" FOREIGN KEY ("period_id") REFERENCES "periods" ("id");
ALTER TABLE "programs" ADD CONSTRAINT "fk_programs_division_id" FOREIGN KEY ("division_id") REFERENCES "divisions" ("id");
ALTER TABLE "programs" ADD CONSTRAINT "fk_programs_owner_user_id" FOREIGN KEY ("owner_user_id") REFERENCES "users" ("id");
ALTER TABLE "public_media" ADD CONSTRAINT "fk_public_media_created_by_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_category_id" FOREIGN KEY ("category_id") REFERENCES "categories" ("id");
ALTER TABLE "treasury_transactions" ADD CONSTRAINT "fk_treasury_transactions_account_id" FOREIGN KEY ("account_id") REFERENCES "treasury_accounts" ("id");
ALTER TABLE "treasury_transactions" ADD CONSTRAINT "fk_treasury_transactions_created_by_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");
ALTER TABLE "users" ADD CONSTRAINT "fk_users_division_id" FOREIGN KEY ("division_id") REFERENCES "divisions" ("id");

CREATE UNIQUE INDEX "attendance_participants_qr_token_unique" ON "attendance_participants" ("qr_token");
CREATE UNIQUE INDEX "categories_name_unique" ON "categories" ("name");
CREATE UNIQUE INDEX "divisions_code_unique" ON "divisions" ("code");
CREATE UNIQUE INDEX "divisions_name_unique" ON "divisions" ("name");
CREATE INDEX "idx_activity_logs_created_at" ON "activity_logs" ("created_at");
CREATE INDEX "idx_activity_logs_entity" ON "activity_logs" ("entity_type", "entity_id");
CREATE INDEX "idx_attendance_events_date" ON "attendance_events" ("event_date");
CREATE INDEX "idx_attendance_events_program_id" ON "attendance_events" ("program_id");
CREATE INDEX "idx_attendance_events_treasury_account" ON "attendance_events" ("treasury_account_id");
CREATE INDEX "idx_attendance_participants_event_name" ON "attendance_participants" ("event_id", "name");
CREATE INDEX "idx_attendance_participants_event_payment" ON "attendance_participants" ("event_id", "payment_status");
CREATE UNIQUE INDEX "idx_attendance_participants_event_phone" ON "attendance_participants" ("event_id", "phone");
CREATE INDEX "idx_attendance_participants_event_status" ON "attendance_participants" ("event_id", "checked_in_at");
CREATE INDEX "idx_attendance_participants_payment_status" ON "attendance_participants" ("payment_status");
CREATE INDEX "idx_membership_options_type_active" ON "membership_options" ("type", "is_active", "sort_order");
CREATE UNIQUE INDEX "idx_membership_options_type_label" ON "membership_options" ("type", "label");
CREATE INDEX "idx_membership_packages_type_active" ON "membership_packages" ("registration_type", "is_active", "sort_order");
CREATE UNIQUE INDEX "idx_membership_packages_type_code" ON "membership_packages" ("registration_type", "code");
CREATE INDEX "idx_membership_registrations_status" ON "membership_registrations" ("payment_status", "created_at");
CREATE INDEX "idx_membership_registrations_treasury" ON "membership_registrations" ("treasury_account_id");
CREATE INDEX "idx_membership_registrations_type" ON "membership_registrations" ("registration_type");
CREATE INDEX "idx_membership_registrations_whatsapp" ON "membership_registrations" ("whatsapp");
CREATE UNIQUE INDEX "idx_notification_runs_user_date" ON "notification_runs" ("user_id", "run_date");
CREATE INDEX "idx_notifications_program_id" ON "notifications" ("program_id");
CREATE INDEX "idx_notifications_user_read" ON "notifications" ("user_id", "is_read", "created_at");
CREATE INDEX "idx_program_approvals_program_id" ON "program_approvals" ("program_id");
CREATE INDEX "idx_program_evaluations_program_id" ON "program_evaluations" ("program_id");
CREATE INDEX "idx_program_expenses_program_date" ON "program_expenses" ("program_id", "expense_date");
CREATE INDEX "idx_program_expenses_task_id" ON "program_expenses" ("task_id");
CREATE INDEX "idx_program_expenses_treasury_account" ON "program_expenses" ("treasury_account_id");
CREATE UNIQUE INDEX "idx_program_feedback_answers_submission_question" ON "program_feedback_answers" ("submission_id", "question_id");
CREATE INDEX "idx_program_feedback_questions_program" ON "program_feedback_questions" ("program_id", "sort_order");
CREATE UNIQUE INDEX "idx_program_feedback_submissions_participant" ON "program_feedback_submissions" ("participant_id");
CREATE INDEX "idx_program_feedback_submissions_program" ON "program_feedback_submissions" ("program_id");
CREATE INDEX "idx_program_incomes_attendance_participant" ON "program_incomes" ("attendance_participant_id");
CREATE INDEX "idx_program_incomes_program_date" ON "program_incomes" ("program_id", "income_date");
CREATE INDEX "idx_program_incomes_task_id" ON "program_incomes" ("task_id");
CREATE INDEX "idx_program_incomes_treasury_account" ON "program_incomes" ("treasury_account_id");
CREATE INDEX "idx_program_lpj_status" ON "program_lpj" ("status");
CREATE INDEX "idx_program_publications_published_featured" ON "program_publications" ("is_published", "is_featured");
CREATE INDEX "idx_program_publications_registration_event" ON "program_publications" ("registration_event_id");
CREATE INDEX "idx_program_task_divisions_division" ON "program_task_divisions" ("division_id", "task_id");
CREATE UNIQUE INDEX "idx_program_task_divisions_unique" ON "program_task_divisions" ("task_id", "division_id");
CREATE INDEX "idx_program_tasks_due_date" ON "program_tasks" ("due_date");
CREATE INDEX "idx_program_tasks_program_status" ON "program_tasks" ("program_id", "status");
CREATE INDEX "idx_programs_division_id" ON "programs" ("division_id");
CREATE INDEX "idx_programs_end_date" ON "programs" ("end_date");
CREATE INDEX "idx_programs_period_status" ON "programs" ("period_id", "status");
CREATE INDEX "idx_public_media_type_active_order" ON "public_media" ("media_type", "is_active", "sort_order");
CREATE INDEX "idx_treasury_transactions_account_date" ON "treasury_transactions" ("account_id", "transaction_date");
CREATE INDEX "idx_treasury_transactions_transfer_group" ON "treasury_transactions" ("transfer_group");
CREATE INDEX "idx_users_division_id" ON "users" ("division_id");
CREATE UNIQUE INDEX "membership_registrations_confirmation_token_unique" ON "membership_registrations" ("confirmation_token");
CREATE UNIQUE INDEX "membership_registrations_registration_code_unique" ON "membership_registrations" ("registration_code");
CREATE UNIQUE INDEX "notifications_dedupe_key_unique" ON "notifications" ("dedupe_key");
CREATE UNIQUE INDEX "periods_name_unique" ON "periods" ("name");
CREATE UNIQUE INDEX "pics_normalized_name_unique" ON "pics" ("normalized_name");
CREATE UNIQUE INDEX "program_lpj_program_id_unique" ON "program_lpj" ("program_id");
CREATE UNIQUE INDEX "programs_program_code_unique" ON "programs" ("program_code");
CREATE UNIQUE INDEX "treasury_accounts_code_unique" ON "treasury_accounts" ("code");
CREATE UNIQUE INDEX "treasury_categories_name_unique" ON "treasury_categories" ("name");
CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email");
