-- PostgreSQL business schema for TDA Pekanbaru VPS migration.
-- Generated from the validated D1 manifest exported on 2026-09-19.
-- Intentionally excludes __appgarden_migrations and VPS auth tables.
-- Foreign keys and secondary/unique indexes are installed after data import.

CREATE TABLE "activities" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" BIGINT,
  "task_title" TEXT DEFAULT '' NOT NULL,
  "action" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "actor" TEXT DEFAULT 'Panitia' NOT NULL,
  "old_data" TEXT,
  "new_data" TEXT,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "undone_at" TEXT
);

CREATE TABLE "activity_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT,
  "entity_type" TEXT NOT NULL,
  "entity_id" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "description" TEXT DEFAULT '' NOT NULL,
  "metadata" TEXT,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "attendance_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "event_date" TEXT NOT NULL,
  "start_time" TEXT DEFAULT '' NOT NULL,
  "end_time" TEXT DEFAULT '' NOT NULL,
  "location" TEXT DEFAULT '' NOT NULL,
  "is_active" BIGINT DEFAULT 1 NOT NULL,
  "created_by_user_id" BIGINT,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "registration_open" BIGINT DEFAULT 1 NOT NULL,
  "program_id" BIGINT,
  "is_paid" BIGINT DEFAULT 0 NOT NULL,
  "public_price" BIGINT DEFAULT 0 NOT NULL,
  "member_price" BIGINT DEFAULT 0 NOT NULL,
  "committee_price" BIGINT DEFAULT 0 NOT NULL,
  "early_bird_public_price" BIGINT DEFAULT 0 NOT NULL,
  "early_bird_member_price" BIGINT DEFAULT 0 NOT NULL,
  "early_bird_committee_price" BIGINT DEFAULT 0 NOT NULL,
  "early_bird_ends_at" TEXT DEFAULT '' NOT NULL,
  "bank_name" TEXT DEFAULT '' NOT NULL,
  "bank_account_number" TEXT DEFAULT '' NOT NULL,
  "bank_account_name" TEXT DEFAULT '' NOT NULL,
  "payment_instructions" TEXT DEFAULT '' NOT NULL,
  "qris_key" TEXT,
  "qris_name" TEXT,
  "qris_type" TEXT,
  "treasury_account_id" BIGINT,
  "feedback_open" BIGINT DEFAULT 0 NOT NULL,
  "income_task_id" BIGINT,
  "public_title" TEXT DEFAULT '' NOT NULL,
  "collaboration_partner" TEXT DEFAULT '' NOT NULL,
  "is_collaboration" BIGINT DEFAULT 0 NOT NULL,
  "flyer_key" TEXT,
  "flyer_name" TEXT,
  "flyer_type" TEXT,
  "allow_public_category" BIGINT DEFAULT 1 NOT NULL,
  "allow_member_category" BIGINT DEFAULT 1 NOT NULL,
  "allow_committee_category" BIGINT DEFAULT 1 NOT NULL
);

CREATE TABLE "attendance_participants" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" BIGINT NOT NULL,
  "name" TEXT NOT NULL,
  "phone" TEXT DEFAULT '' NOT NULL,
  "category" TEXT DEFAULT 'Member' NOT NULL,
  "organization" TEXT DEFAULT '' NOT NULL,
  "qr_token" TEXT NOT NULL,
  "checked_in_at" TEXT,
  "check_in_method" TEXT,
  "checked_in_by_user_id" BIGINT,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "passport_number" TEXT DEFAULT '' NOT NULL,
  "amount_due" BIGINT DEFAULT 0 NOT NULL,
  "price_label" TEXT DEFAULT 'Gratis' NOT NULL,
  "payment_status" TEXT DEFAULT 'not_required' NOT NULL,
  "payment_method" TEXT DEFAULT '' NOT NULL,
  "payment_proof_key" TEXT,
  "payment_proof_name" TEXT,
  "payment_proof_type" TEXT,
  "payment_confirmed_at" TEXT,
  "payment_verified_at" TEXT,
  "payment_verified_by_user_id" BIGINT,
  "payment_note" TEXT DEFAULT '' NOT NULL,
  "payment_verification_source" TEXT DEFAULT '' NOT NULL,
  "payment_received_amount" BIGINT DEFAULT 0 NOT NULL,
  "payment_paid_at" TEXT,
  "payment_treasury_account_id" BIGINT,
  "payment_received_by_user_id" BIGINT,
  "payment_received_at" TEXT
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "sort_order" BIGINT DEFAULT 0 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "divisions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "sort_order" BIGINT DEFAULT 0 NOT NULL,
  "is_active" BIGINT DEFAULT 1 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "membership_options" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "sort_order" BIGINT DEFAULT 0 NOT NULL,
  "is_active" BIGINT DEFAULT 1 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "membership_packages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "registration_type" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "amount" BIGINT DEFAULT 0 NOT NULL,
  "includes_shirt" BIGINT DEFAULT 0 NOT NULL,
  "includes_class" BIGINT DEFAULT 0 NOT NULL,
  "is_recommended" BIGINT DEFAULT 0 NOT NULL,
  "sort_order" BIGINT DEFAULT 0 NOT NULL,
  "is_active" BIGINT DEFAULT 1 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "membership_registrations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "registration_code" TEXT NOT NULL,
  "registration_type" TEXT NOT NULL,
  "full_name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "whatsapp" TEXT NOT NULL,
  "business_name" TEXT DEFAULT '' NOT NULL,
  "business_field" TEXT NOT NULL,
  "business_age" TEXT NOT NULL,
  "employee_count" BIGINT DEFAULT 0 NOT NULL,
  "annual_revenue" TEXT NOT NULL,
  "previous_training" TEXT DEFAULT '' NOT NULL,
  "business_issues" TEXT DEFAULT '[]' NOT NULL,
  "existing_systems" TEXT DEFAULT '[]' NOT NULL,
  "tda_goal" TEXT DEFAULT '' NOT NULL,
  "information_source" TEXT DEFAULT '' NOT NULL,
  "package_code" TEXT NOT NULL,
  "package_name" TEXT NOT NULL,
  "amount_due" BIGINT NOT NULL,
  "includes_shirt" BIGINT DEFAULT 0 NOT NULL,
  "shirt_size" TEXT DEFAULT '' NOT NULL,
  "treasury_account_id" BIGINT,
  "payment_method" TEXT DEFAULT '' NOT NULL,
  "payment_status" TEXT DEFAULT 'pending' NOT NULL,
  "payment_proof_key" TEXT,
  "payment_proof_name" TEXT,
  "payment_proof_type" TEXT,
  "payment_confirmed_at" TEXT,
  "payment_verified_at" TEXT,
  "payment_verified_by_user_id" BIGINT,
  "payment_received_amount" BIGINT DEFAULT 0 NOT NULL,
  "payment_paid_at" TEXT,
  "payment_note" TEXT DEFAULT '' NOT NULL,
  "member_status" TEXT DEFAULT 'menunggu_pembayaran' NOT NULL,
  "shirt_status" TEXT DEFAULT 'belum_diproses' NOT NULL,
  "confirmation_token" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "passport_number" TEXT DEFAULT '' NOT NULL,
  "sleeve_type" TEXT DEFAULT '' NOT NULL
);

CREATE TABLE "membership_settings" (
  "id" BIGINT PRIMARY KEY,
  "admin_whatsapp" TEXT DEFAULT '6285121804468' NOT NULL,
  "treasury_account_id" BIGINT,
  "qris_key" TEXT,
  "qris_name" TEXT,
  "qris_type" TEXT,
  "payment_instructions" TEXT DEFAULT '' NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "notification_runs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "run_date" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "program_id" BIGINT,
  "type" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "message" TEXT DEFAULT '' NOT NULL,
  "dedupe_key" TEXT NOT NULL,
  "is_read" BIGINT DEFAULT 0 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "periods" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "start_date" TEXT NOT NULL,
  "end_date" TEXT NOT NULL,
  "is_active" BIGINT DEFAULT 0 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "pics" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "normalized_name" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "program_approvals" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_id" BIGINT NOT NULL,
  "approver_user_id" BIGINT,
  "status" TEXT DEFAULT 'pending' NOT NULL,
  "note" TEXT DEFAULT '' NOT NULL,
  "sequence" BIGINT DEFAULT 1 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "program_evaluations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_id" BIGINT NOT NULL,
  "indicator" TEXT NOT NULL,
  "target_value" DOUBLE PRECISION NOT NULL,
  "actual_value" DOUBLE PRECISION DEFAULT 0 NOT NULL,
  "unit" TEXT DEFAULT '' NOT NULL,
  "is_measured" BIGINT DEFAULT 0 NOT NULL,
  "notes" TEXT DEFAULT '' NOT NULL,
  "created_by_user_id" BIGINT,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "program_expenses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_id" BIGINT NOT NULL,
  "description" TEXT NOT NULL,
  "category" TEXT DEFAULT 'Lainnya' NOT NULL,
  "expense_date" TEXT NOT NULL,
  "amount" BIGINT DEFAULT 0 NOT NULL,
  "receipt_key" TEXT,
  "receipt_name" TEXT,
  "receipt_type" TEXT,
  "created_by_user_id" BIGINT,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "treasury_account_id" BIGINT,
  "task_id" BIGINT
);

CREATE TABLE "program_feedback_answers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "submission_id" BIGINT NOT NULL,
  "question_id" BIGINT NOT NULL,
  "answer_json" TEXT DEFAULT '' NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "program_feedback_questions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_id" BIGINT NOT NULL,
  "question" TEXT NOT NULL,
  "question_type" TEXT DEFAULT 'paragraph' NOT NULL,
  "options_json" TEXT DEFAULT '[]' NOT NULL,
  "is_required" BIGINT DEFAULT 0 NOT NULL,
  "sort_order" BIGINT DEFAULT 0 NOT NULL,
  "is_active" BIGINT DEFAULT 1 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "program_feedback_submissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_id" BIGINT NOT NULL,
  "event_id" BIGINT NOT NULL,
  "participant_id" BIGINT NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "program_incomes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_id" BIGINT NOT NULL,
  "description" TEXT NOT NULL,
  "source" TEXT DEFAULT 'Lainnya' NOT NULL,
  "income_date" TEXT NOT NULL,
  "amount" BIGINT DEFAULT 0 NOT NULL,
  "receipt_key" TEXT,
  "receipt_name" TEXT,
  "receipt_type" TEXT,
  "created_by_user_id" BIGINT,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "treasury_account_id" BIGINT,
  "attendance_participant_id" BIGINT,
  "task_id" BIGINT
);

CREATE TABLE "program_lpj" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_id" BIGINT NOT NULL,
  "status" TEXT DEFAULT 'belum_dibuat' NOT NULL,
  "summary" TEXT DEFAULT '' NOT NULL,
  "result" TEXT DEFAULT '' NOT NULL,
  "evaluation" TEXT DEFAULT '' NOT NULL,
  "submitted_at" TEXT,
  "completed_at" TEXT,
  "updated_by_user_id" BIGINT,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "program_publications" (
  "program_id" BIGINT PRIMARY KEY,
  "is_published" BIGINT DEFAULT 0 NOT NULL,
  "public_title" TEXT DEFAULT '' NOT NULL,
  "tagline" TEXT DEFAULT '' NOT NULL,
  "description" TEXT DEFAULT '' NOT NULL,
  "benefits" TEXT DEFAULT '' NOT NULL,
  "audience" TEXT DEFAULT '' NOT NULL,
  "contact_name" TEXT DEFAULT '' NOT NULL,
  "contact_phone" TEXT DEFAULT '' NOT NULL,
  "registration_event_id" BIGINT,
  "is_featured" BIGINT DEFAULT 0 NOT NULL,
  "flyer_key" TEXT,
  "flyer_name" TEXT,
  "flyer_type" TEXT,
  "updated_by_user_id" BIGINT,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "program_task_divisions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" BIGINT NOT NULL,
  "division_id" BIGINT NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "program_tasks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_id" BIGINT NOT NULL,
  "title" TEXT NOT NULL,
  "pic" TEXT DEFAULT '' NOT NULL,
  "due_date" TEXT DEFAULT '' NOT NULL,
  "status" TEXT DEFAULT 'belum_mulai' NOT NULL,
  "notes" TEXT DEFAULT '' NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "uses_budget" BIGINT DEFAULT 0 NOT NULL,
  "budget_amount" BIGINT DEFAULT 0 NOT NULL,
  "income_target" BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE "programs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_code" TEXT NOT NULL,
  "period_id" BIGINT NOT NULL,
  "division_id" BIGINT NOT NULL,
  "owner_user_id" BIGINT,
  "title" TEXT NOT NULL,
  "summary" TEXT DEFAULT '' NOT NULL,
  "status" TEXT DEFAULT 'draft' NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "pic" TEXT DEFAULT '' NOT NULL,
  "start_date" TEXT DEFAULT '' NOT NULL,
  "end_date" TEXT DEFAULT '' NOT NULL,
  "target" TEXT DEFAULT '' NOT NULL,
  "budget" BIGINT DEFAULT 0 NOT NULL,
  "income_budget" BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE "public_media" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "media_type" TEXT DEFAULT 'banner' NOT NULL,
  "title" TEXT DEFAULT '' NOT NULL,
  "description" TEXT DEFAULT '' NOT NULL,
  "event_date" TEXT DEFAULT '' NOT NULL,
  "link_url" TEXT DEFAULT '' NOT NULL,
  "image_key" TEXT NOT NULL,
  "image_name" TEXT DEFAULT '' NOT NULL,
  "image_type" TEXT DEFAULT 'image/webp' NOT NULL,
  "sort_order" BIGINT DEFAULT 0 NOT NULL,
  "is_active" BIGINT DEFAULT 1 NOT NULL,
  "created_by_user_id" BIGINT,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "tasks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" BIGINT NOT NULL,
  "title" TEXT NOT NULL,
  "pic" TEXT DEFAULT '' NOT NULL,
  "due_date" TEXT NOT NULL,
  "priority" TEXT DEFAULT 'Sedang' NOT NULL,
  "status" TEXT DEFAULT 'Belum Mulai' NOT NULL,
  "notes" TEXT DEFAULT '' NOT NULL,
  "sort_order" BIGINT DEFAULT 0 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "deleted_at" TEXT
);

CREATE TABLE "treasury_accounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "type" TEXT DEFAULT 'bank' NOT NULL,
  "bank_name" TEXT DEFAULT '' NOT NULL,
  "account_number" TEXT DEFAULT '' NOT NULL,
  "account_holder" TEXT DEFAULT '' NOT NULL,
  "opening_balance" BIGINT DEFAULT 0 NOT NULL,
  "sort_order" BIGINT DEFAULT 0 NOT NULL,
  "is_active" BIGINT DEFAULT 1 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "treasury_categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "sort_order" BIGINT DEFAULT 0 NOT NULL,
  "is_active" BIGINT DEFAULT 1 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "treasury_transactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" BIGINT NOT NULL,
  "direction" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "category" TEXT DEFAULT 'Lainnya' NOT NULL,
  "transaction_date" TEXT NOT NULL,
  "amount" BIGINT NOT NULL,
  "transfer_group" TEXT,
  "created_by_user_id" BIGINT,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT,
  "role" TEXT DEFAULT 'viewer' NOT NULL,
  "division_id" BIGINT,
  "is_active" BIGINT DEFAULT 1 NOT NULL,
  "created_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
  "updated_at" TEXT DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);
