BEGIN;

CREATE TABLE IF NOT EXISTS public_site_settings (
  id BIGINT PRIMARY KEY,
  site_name TEXT DEFAULT 'TDA Pekanbaru' NOT NULL,
  site_tagline TEXT DEFAULT '' NOT NULL,
  site_description TEXT DEFAULT '' NOT NULL,

  logo_key TEXT,
  favicon_key TEXT,

  contact_whatsapp TEXT DEFAULT '' NOT NULL,
  contact_email TEXT DEFAULT '' NOT NULL,
  address TEXT DEFAULT '' NOT NULL,

  instagram_url TEXT DEFAULT '' NOT NULL,
  youtube_url TEXT DEFAULT '' NOT NULL,
  linkedin_url TEXT DEFAULT '' NOT NULL,
  tiktok_url TEXT DEFAULT '' NOT NULL,

  footer_text TEXT DEFAULT '' NOT NULL,

  seo_title TEXT DEFAULT '' NOT NULL,
  seo_description TEXT DEFAULT '' NOT NULL,

  updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,

  created_at TEXT DEFAULT (
    to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    'YYYY-MM-DD HH24:MI:SS')
  ) NOT NULL,

  updated_at TEXT DEFAULT (
    to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    'YYYY-MM-DD HH24:MI:SS')
  ) NOT NULL,

  CONSTRAINT public_site_settings_singleton CHECK (id = 1)
);

INSERT INTO public_site_settings (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;


CREATE TABLE IF NOT EXISTS public_site_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  section_key TEXT NOT NULL UNIQUE,
  section_type TEXT DEFAULT 'content' NOT NULL,

  eyebrow TEXT DEFAULT '' NOT NULL,
  title TEXT DEFAULT '' NOT NULL,
  subtitle TEXT DEFAULT '' NOT NULL,
  body TEXT DEFAULT '' NOT NULL,

  image_key TEXT,
  image_name TEXT,
  image_type TEXT,

  primary_cta_label TEXT DEFAULT '' NOT NULL,
  primary_cta_url TEXT DEFAULT '' NOT NULL,

  secondary_cta_label TEXT DEFAULT '' NOT NULL,
  secondary_cta_url TEXT DEFAULT '' NOT NULL,

  content_json TEXT DEFAULT '{}' NOT NULL,

  status TEXT DEFAULT 'draft' NOT NULL,
  is_visible BIGINT DEFAULT 1 NOT NULL,
  sort_order BIGINT DEFAULT 0 NOT NULL,

  published_at TEXT,

  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,

  created_at TEXT DEFAULT (
    to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    'YYYY-MM-DD HH24:MI:SS')
  ) NOT NULL,

  updated_at TEXT DEFAULT (
    to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    'YYYY-MM-DD HH24:MI:SS')
  ) NOT NULL,

  CONSTRAINT public_site_sections_status_check
    CHECK (status IN ('draft', 'published', 'archived')),

  CONSTRAINT public_site_sections_visible_check
    CHECK (is_visible IN (0, 1))
);

CREATE INDEX IF NOT EXISTS idx_public_site_sections_status_order
  ON public_site_sections(status, is_visible, sort_order);


CREATE TABLE IF NOT EXISTS public_navigation_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  location TEXT DEFAULT 'header' NOT NULL,
  label TEXT NOT NULL,
  href TEXT NOT NULL,

  parent_id BIGINT REFERENCES public_navigation_items(id)
    ON DELETE CASCADE,

  sort_order BIGINT DEFAULT 0 NOT NULL,
  is_active BIGINT DEFAULT 1 NOT NULL,

  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,

  created_at TEXT DEFAULT (
    to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    'YYYY-MM-DD HH24:MI:SS')
  ) NOT NULL,

  updated_at TEXT DEFAULT (
    to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    'YYYY-MM-DD HH24:MI:SS')
  ) NOT NULL,

  CONSTRAINT public_navigation_location_check
    CHECK (location IN ('header', 'footer')),

  CONSTRAINT public_navigation_active_check
    CHECK (is_active IN (0, 1))
);

CREATE INDEX IF NOT EXISTS idx_public_navigation_location_order
  ON public_navigation_items(location, is_active, sort_order);

COMMIT;
